### ISSUE TITLE
Update tags from upstream

### ISSUE THREAD

**Issue by tinywrkb** [lbonn/rofi#10]
I package this Wayland fork as an [AUR package](https://aur.archlinux.org/packages/rofi-lbonn-wayland-git/) for Arch Linux, and it would be nice if the auto-generated package version will show correctly that the fork is incorporating the latest release and this requires that the fork will have the latest (relevant) tags in the git repo.

```
git fetch davatorium-rofi
git push --tags origin
```

The command that I use for generating the package version is `git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'` and its current output is `1.3.1.r1349.gf0139710`.  
With the tags in the repo, it will generate `1.6.0.r23.gf0139710`.

**Comment by lbonn** [comment]
Ow the tags were really outdated, thanks.
