### ISSUE TITLE
[REQUEST] put a tag for 1.7.5-wayland3

### ISSUE THREAD

**Issue by aacebedo** [lbonn/rofi#100]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I cannot access to all fixes since July on Nixos

### How do you know that this problem exists today? Why is this important?

Version in nixos are based on tags so I am stuck with 1.7.5-wayland2

### Who will benefit from it?

Everyone using nixos

### Rofi version (rofi -v)

1.7.5

### Configuration

N/A

**Comment by lbonn** [comment]
I'd like to close #97 before tagging a new version.

In the meantime, NixOS is a actually a good system to use if you want to customize some package. Example in a nix-shell:

```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
  packages = with pkgs; [
    (pkgs.callPackage "${toString pkgs.path}/pkgs/applications/misc/rofi/wrapper.nix" {
      rofi-unwrapped = (pkgs.rofi-wayland.unwrapped.overrideAttrs (oldAttrs: {
        src = pkgs.fetchFromGitHub {
              owner = "lbonn";
              repo = "rofi";
              rev = "78888dd80ddb49a5b3296e55e94aaa41c0f43298";
              fetchSubmodules = true;
              sha256 = "sha256-ab1X3w6E1hsOAjqroWm9/vpuaSjMKvdv5RHsP9sVPsU=";
        };
      }));
    })
  ];
}
```

For a system-wide change, you can use it in `config.packageOverrides`: https://nixos.org/guides/nix-pills/nixpkgs-overriding-packages.html#id1450

**Comment by aacebedo** [comment]
> I'd like to close #97 before tagging a new version.
> 
> In the meantime, NixOS is a actually a good system to use if you want to customize some package. Example in a nix-shell:
> 
> ```nix
> { pkgs ? import <nixpkgs> {} }:
> 
> pkgs.mkShell {
>   LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
>   packages = with pkgs; [
>     (pkgs.callPackage "${toString pkgs.path}/pkgs/applications/misc/rofi/wrapper.nix" {
>       rofi-unwrapped = (pkgs.rofi-wayland.unwrapped.overrideAttrs (oldAttrs: {
>         src = pkgs.fetchFromGitHub {
>               owner = "lbonn";
>               repo = "rofi";
>               rev = "78888dd80ddb49a5b3296e55e94aaa41c0f43298";
>               fetchSubmodules = true;
>               sha256 = "sha256-ab1X3w6E1hsOAjqroWm9/vpuaSjMKvdv5RHsP9sVPsU=";
>         };
>       }));
>     })
>   ];
> }
> ```
> 
> For a system-wide change, you can use it in `config.packageOverrides`: https://nixos.org/guides/nix-pills/nixpkgs-overriding-packages.html#id1450

Thanks for the response ! I wanted to update the general repo but I'll override the package then in my flake instead.
