### ISSUE TITLE
[BUG] theme_parser FAIL ? 

### ISSUE THREAD

**Issue by lavara123** [lbonn/rofi#103]
### Rofi version (rofi -v or git commit in case of build issue)

last

### Configuration

/.cache/yay/rofi-lbonn-wayland-git/src/build/theme_parser.test

### Theme

/.cache/yay/rofi-lbonn-wayland-git/src/build/theme_parser.test

### Launch command

rofi

### Step to reproduce

https://github.com/prasanthrangan/hyprdots

### Expected behavior

-

### Actual behavior

-

### Additional information

>>> ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MALLOC_PERTURB_=97 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 /home/sebe/.cache/yay/rofi-lbonn-wayland-git/src/build/theme_parser.test

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
I don't see this test failing on either latest master or the 1.7.5+wayland2 release.

@lavara123 Please re-open with version information and more logs if this is still an issue
