### ISSUE TITLE
[BUG] zwlr_layer_surface_v1@12: error 1: width 0 requested without setting left and right anchors

### ISSUE THREAD

**Issue by Xyene** [lbonn/rofi#11]
Hi,

First off -- thanks for providing this package! It's a much nicer experience than upstream rofi on Wayland.

This issue is not present in any current release of Sway, but using latest rofi on latest sway/wlroots:

```
$ rofi
zwlr_layer_surface_v1@12: error 1: width 0 requested without setting left and right anchors
```

The cause is likely https://github.com/swaywm/wlroots/commit/8dec751a6d84335fb04288b8efab6dd5c90288d3 (https://github.com/swaywm/wlroots/pull/2422).

**Comment by lbonn** [comment]
Thanks for the heads up!

Should be fixed with https://github.com/lbonn/rofi/commit/74a157c644ed2b32f46ff9ce9f2bf0d6d0fbf201

**Comment by Xyene** [comment]
Awesome, thanks for the quick fix!
