### ISSUE TITLE
[BUG] Arch package not found

### ISSUE THREAD

**Issue by jagjordi** [lbonn/rofi#128]
### Rofi version (rofi -v or git commit in case of build issue)

N/A

### Configuration

N/A

### Theme

N/A

### Launch command

N/A

### Step to reproduce

```
sudo pacman -Syu rofi-wayland
```

### Expected behavior

Package gets installed

### Actual behavior

```
➜  ~ sudo pacman -Syu rofi-wayland
:: Synchronizing package databases...
 core is up to date
 extra is up to date
error: target not found: rofi-wayland
```

### Additional information

old package works `yay -S rofi-lbonn-wayland-git`

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by Ferdi265** [comment]
I'm also using Arch and I can't reproduce this. Maybe you are using an out-of-date mirror?

You can either try a different mirror in your `/etc/pacman.d/mirrorlist` or use a tool like `reflector` to sort your mirror list in a way that prefers up-to-date mirrors.

**Comment by wrxx011** [comment]
It's not a bug, the package was moved to main repos
now its known as `extra/rofi-wayland`

The git package is still in the aur so that's the reason why it works

**Comment by lbonn** [comment]
Thanks for the additional details! Moreover, this is not really a "bug" with rofi itself
