### ISSUE TITLE
[BUG] - Private desktop files not shown in run

### ISSUE THREAD

**Issue by tigerjack** [lbonn/rofi#13]
## Version

Output of `rofi -v`
`Version: 1.6.0-65-g87b48ce7 (makepkg)`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
[gist](https://gist.github.com/tigerjack/2871026af17b60899cb0d0053372c321)

## Launch Command

`The commandline used to launch **rofi**`
`rofi -show`

## Steps to reproduce
Just run rofi

## What behaviour you see

Desktop files under `~/.config/autostart/` are not shown in the drun output.

## What behaviour you expect to see

All files should be present

**Comment by lbonn** [comment]
Does not seem to be wayland-related. Feel free to reopen if it works on upstream rofi.
