### ISSUE TITLE
[REQUEST] Add a fix for icons path for main line Rofi. 

### ISSUE THREAD

**Issue by musicfunfan** [lbonn/rofi#132]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

In the main line Rofi there is a [fix](https://github.com/davatorium/rofi/commit/9b6e70b365116935158413034cf2aeb16affd9d4). I want that added to this fork. In order to have icons on the applications that do not have ``.png`` and the ``.svg`` extensions. 

### How do you know that this problem exists today? Why is this important?

I know this problem exist. Because i use the AM package manager for appimages. And the icons do  not displayed on the Rofi. I did the research and find this[ issue](https://github.com/davatorium/rofi/issues/1977).  

### Who will benefit from it?

I think all the people use packages that the icons do not have the file extensions will be benefit from this change. 

### Rofi version (rofi -v)

Version: 1.7.5+wayland2-1-gff2338c3

### Configuration

My config files is [here](https://gitlab.com/musicfunfan/main_configs_files/-/blob/main/rofi/launchpad.rasi?ref_type=heads). 

### Additional information

I use archlinux. BTW

**Comment by lbonn** [comment]
@musicfunfan the fix commit you are referring to is present in the wayland branch (I've merged upstream changes a couple of days ago).

Maybe you can try it on a fresh build?

**Comment by musicfunfan** [comment]
I do not see an update on the AUR. 

```bash
yay -Sua
:: Searching AUR for updates...
 -> Packages not in AUR: stacer
 there is nothing to do
```
Is it updated on A.U.R. ? 

What do you mean with term "fresh build" ?

**Comment by musicfunfan** [comment]
So... i re-install the package this time form archrepo i did not know that [this ](https://archlinux.org/packages/extra/x86_64/rofi-wayland/)package was on the arch repo... But i have the same problem... Is there anything more i can try ? Did i do something wrong here?

If anyone knows something about this feel free to mention me. Thanks in advance. 😉

**Comment by lbonn** [comment]
@musicfunfan this package contains the latest released version, without this fix. If you really need a fix from the latest version on git and you are using AUR, this is probably what you are looking for: https://aur.archlinux.org/packages/rofi-lbonn-wayland-git

**Comment by musicfunfan** [comment]
Ok, yea i use A.U.R. This fix will included on the latest release ? If yes then i am happy to wait, because its not a big problem and i try when its possible not to use the A.U.R. when an official package exist. 
Just let me know if the A.U.R. (git package) will be the official package some day.

Anyway, thanks for the answer and your time.
