### ISSUE TITLE
[BUG] Laptop touchpad is not working for scrolling through rofi elements

### ISSUE THREAD

**Issue by mylinuxforwork** [lbonn/rofi#134]
### Rofi version (rofi -v or git commit in case of build issue)

Version 1.7.5+wayland3

### Configuration

https://gist.github.com/mylinuxforwork/534833190d0e630a8b3345aff0450c8b

### Theme

https://gist.github.com/mylinuxforwork/029133965efdfc77828535243d435388

### Launch command

rofi -dmenu -i -replace -config ~/dotfiles/rofi/config-wallpaper.rasi

### Step to reproduce

* Open rofi
* Use scrolling gesture on laptop touchpad 
* No scrolling

### Expected behavior

Should scroll with scroll feature on touchpad or touchscreen (2 fingers swipe)

### Actual behavior

No scrolling. Only the mouse scrollwheel and the arrow keys are working

### Additional information

I am using rofi-wayland package on Hyprland

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
@mylinuxforwork It should work again, though I guessed the speed to make it roughly as fast as scrolling on my terminal. No time for going through the specs rabbit hole and find out what is the proper computation :).

**Comment by mylinuxforwork** [comment]
@lbonn Thank you. Will check when the next release is available as AUR.

**Comment by donovanglover** [comment]
+1 for a release so users can update from 1.7.5+wayland3 and get this fix
