### ISSUE TITLE
[BUG] Rofi crashes after launch with "listener function for opcode 1 of wl_data_device is NULL"

### ISSUE THREAD

**Issue by c0smicdev** [lbonn/rofi#136]
### Rofi version (rofi -v or git commit in case of build issue)

Version: 1.7.5+wayland3

### Configuration

https://gist.github.com/c0smicdev/dcc3a349a41b6bd2513d55b9858317c5

### Theme

https://gist.github.com/c0smicdev/70f80556ab1e8f17667ff4bdbae19cb4

### Launch command

rofi -show drun

### Step to reproduce

Launch rofi

### Expected behavior

Rofi launches and shows a menu from which to launch files

### Actual behavior

Rofi launches but immediately crashes with the following output: 

```
(process:10698): Theme-WARNING **: 10:08:06.114: Found more then 20 redirects for property. Stopping.

(process:10698): Modes.Window-WARNING **: 10:08:06.136: Unsupported window field name :role. Wayland window switcher supports only 'title' and 'app-id' ('class') fields

(process:10698): Modes.Window-WARNING **: 10:08:06.136: Unsupported window field name :name. Wayland window switcher supports only 'title' and 'app-id' ('class') fields

(process:10698): Modes.Window-WARNING **: 10:08:06.136: Unsupported window field name :desktop. Wayland window switcher supports only 'title' and 'app-id' ('class') fields
listener function for opcode 1 of wl_data_device is NULL
fish: Job 1, 'rofi -show drun' terminated by signal SIGABRT (Abort)
```

### Additional information

The issue is similar to #65.

I recently updated all my packages with `pacman -Syu`, so an incompatibility between package versions may be causing the error.

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
@c0smicdev thanks for the report! What compositor do you use (and which version)? It is also an issue on recent KDE?

**Comment by lbonn** [comment]
@c0smicdev can you test again with latest revision in the wayland branch? (d88b475bad26a6ba60c85cd7830e441da5774cdb)

**Comment by c0smicdev** [comment]
@lbonn I'm on hyprland, and with the latest version the bug doesn't appear. However, the bug disappeared on the latest stable release a bit after submitting the bug report. I have no idea why; the only thing I might have done is editing a `.desktop` file in `/usr/share/applications`.
Thanks for the help though

**Comment by lbonn** [comment]
Thanks for the details, then it looks like this https://github.com/hyprwm/Hyprland/issues/6444

But anyway, fixing it in rofi looked like the correct thing to do, given the comments here for example https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/341
