### ISSUE TITLE
[BUG]  wlroots 0.12

### ISSUE THREAD

**Issue by exdeniz** [lbonn/rofi#14]
```
zwlr_layer_surface_v1@12: error 1: width 0 requested without setting left and right anchors
```
Please fix with wlroots 0.12

**Comment by lbonn** [comment]
What version do you use?

See #11, #16

**Comment by exdeniz** [comment]
Latest form AUR

**Comment by lbonn** [comment]
Please paste the output of `rofi -version`

**Comment by exdeniz** [comment]
I reinstall from AUR and everything worked. Thank you, you can close it.
