### ISSUE TITLE
[BUG]  -disable-history not working

### ISSUE THREAD

**Issue by haennes** [lbonn/rofi#149]
### Rofi version (rofi -v or git commit in case of build issue)

Version: 1.7.5+wayland3

### Configuration

https://gist.github.com/haennes/9b100643da1e93aa4ea9845688002d83

### Theme

  https://gist.github.com/haennes/494f96e6a339701f9bb2422639d0c223

### Launch command

rofi -dmenu -disable-history -no-fixed-num-lines -l 1 -i -input /dev/null -password -p "Passphrase:"

### Step to reproduce

run `rofi -dmenu -disable-history -no-fixed-num-lines -l 1 -i -input /dev/null -password -p "Passphrase:"`

### Expected behavior

doesnt write anything to $XDG_CACHE_HOME/rofi-entry-history.txt (i.e. ~/.cache/rofi-entry-history.txt)

### Actual behavior

outputs a password to this file

### Additional information

See davatorium/rofi#1995
Sorry that i didnt report that here earlier, thought it would be merged anyways

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by haennes** [comment]
Bump as this is a severe issue :)

**Comment by lbonn** [comment]
It should be fixed in 0a0cc5f6d7b6d028cc7f6140edf5416d187b3696.

Reopen if it persists.
