### ISSUE TITLE
[BUG] Rofi wayland broken plugins api

### ISSUE THREAD

**Issue by rkmax** [lbonn/rofi#151]
### Rofi version (rofi -v or git commit in case of build issue)

1.7.5+wayland3-2

### Configuration

https://gist.github.com/rkmax/a25619b639f5a742ad78a42010a69da9

### Theme

https://gist.github.com/rkmax/83b6da7997e8b77012c99d208ef71319

### Launch command

rofi -show vscode-recent -modi vscode-recent

### Step to reproduce

- yay -S rofi-vscode-mode
- pacman -S rofi-wayland
- rofi

### Expected behavior

To work as work on the regular rofi version 1.7.5

### Actual behavior

When the vscode-recent is not recognized. you'll see a notice

```
(process:56661): Rofi-WARNING **: 09:43:21.239: ABI version of plugin: 'librofi_vscode_mode.so' does not match: 00000006 expecting: 00000007
```

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
See https://github.com/lbonn/rofi/issues/96 and the release notes https://github.com/lbonn/rofi/releases/tag/1.7.5%2Bwayland3

It will be resolved when upstream rofi releases a new version and we sync with it.

In the meantime, you'll have to rebuild the plugin from source against this fork's headers.
