### ISSUE TITLE
[REQUEST] auto close when unfocused

### ISSUE THREAD

**Issue by littleblack111** [lbonn/rofi#152]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

close when unfocused

### How do you know that this problem exists today? Why is this important?

when i try to click outside of rofi, its unfocused and inputs such as typing is to other places

### Who will benefit from it?

everyone

### Rofi version (rofi -v)

Version: 1.7.5+wayland3

### Configuration

doesnt matter

### Additional information

maybe https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:enum:keyboard_interactivity

**Comment by lbonn** [comment]
You've already opened #148

**Comment by littleblack111** [comment]
Oh sry. I'm forgetful
