### ISSUE TITLE
[BUG] moving a container while rofi is active switches workspaces

### ISSUE THREAD

**Issue by berezowski** [lbonn/rofi#157]
### Rofi version (rofi -v or git commit in case of build issue)

Version: 1.7.5+wayland3

### Configuration

https://gist.github.com/berezowski/d6d60a183a5b464e50b39e8ced3eb705

### Theme

https://gist.github.com/berezowski/80ea3ae4bd2697993e40c2b7086f217f

### Timing report

https://gist.github.com/berezowski/23511fec971d6393aafcd3ba74b367d0

### Launch command

rofi -show

### Step to reproduce

* go to empty workspace [workspace1]
* create any window [window1]
* rofi -show
* press keyboard binding to move [window1] to another workspace [workspace2]

### Expected behavior

* focus remains on [workspace1]

### Actual behavior

* focus switches to [workspace2]

if there were other windows on [workspace1]:
* sometimes all remaining windows on [workspace1] are focused (the parent/root container is selected)

### Additional information

i stumbled upon the issue with a custom workspace switcher (see video below). 
But the same behaviour applies to the default "move container to workspace" command.
https://github.com/user-attachments/assets/536f8878-20c6-4f8e-b6e6-ee018bdb2210

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [x] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
@berezowski I had a similar problem working with a window switcher as a plugin

It's not a rofi issue but a compositor behavior, I think they see it as a security policy: you are switching workspace while a layer shell has keyboard focus and when the layer shell is destroyed the compositor is going back to the workspace you started with.

See:

https://github.com/lbonn/i3-focus-last/blob/c5f7bf8546aad02adbbf35d8a3baec9b1b2cc507/rofi-window-i3/src/lib.rs#L70

This is also related https://github.com/lbonn/rofi/issues/117

**Comment by berezowski** [comment]
Ok, Thanks.

P.S.
About your rofi_view_hide(); call.
Couldn't rofi do this by default before running the external command a second time?
