### ISSUE TITLE
[BUG] incorrect mouse click behaviour

### ISSUE THREAD

**Issue by semka95** [lbonn/rofi#19]
## Version

Version: 1.6.1-wayland

## Configuration

 [gist](https://gist.github.com/semka95/3a179d386c649a9abaea89729969f761#file-help)

## Launch Command

rofi -dmenu -p "How to make a screenshot?" << EOF
 Screenshot Fullscreen
 Screenshot Focused
 Screenshot Selected Window
 Screenshot Selected Output
 Screenshot Region
 Record Focused
 Record Selected Window
 Record Selected Output
 Record Region
 Screenshare
EOF

[link](https://gist.github.com/semka95/3a179d386c649a9abaea89729969f761#file-script) to full script

## Steps to reproduce

- Run rofi
- Double click on menu item

## What behaviour you see

I can't choose output/window, when I double click on menu item (for example  "Screenshot Selected Window"), looks like it registers my double click as I'm choose window.
Everything works fine when I'm using keyboard.
Watch video if you don't understand.

## What behaviour you expect to see

Not register click after clicking menu option.

**Additional details:**
- Link to my [config](https://gist.github.com/semka95/3a179d386c649a9abaea89729969f761#file-config-rasi).
- Video
First time I'm taking screenshot using my keyboard, I can choose window, everything work as intended. Second time I'm double clicking same option, and it registered my double click as I'm choose window.
Same thing happen if I'm running rofi with "-me-select-entry ' ' -me-accept-entry MousePrimary" options.

https://user-images.githubusercontent.com/4162760/103455225-6bdc4780-4cfc-11eb-8f25-262633b80ebe.mp4

**Comment by lbonn** [comment]
Looks like slurp is getting the mouse event immediately when it starts, not sure if we can do anything for that from rofi.

As a work-around you can add `sleep 0.1` in you script after the `CHOICE` assignment.

**Comment by semka95** [comment]
Yeah, adding sleep fixes problem, thank you.
Looks like it's not rofi problem.
