### ISSUE TITLE
[REQUEST] Style With GTK Named Colors

### ISSUE THREAD

**Issue by bagnaram** [lbonn/rofi#21]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Before creating a feature request
- [X] I checked the *next* branch to see if the feature has already been
  implemented
- [X] I searched existing reports to see if it is already requested.

## What is the user problem or growth opportunity you want to see solved?

In order to support a seamless experience across applications, it would be great  if rofi honored global GTK colors defined in https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-22/gtk/theme/Adwaita/_colors-public.scss

## How do you know that this problem exists today? Why is this important?

Currently specifying colors via the `foreground: @theme_fg_color;` results in parse errors upon rofi launch.

## Who will benefit from it?

Theme creation will be able to inherit the  user's environment

## Version

Version: 1.6.1-wayland

## Configuration

N/A

**Comment by lbonn** [comment]
This does not look wayland specific. Is it implemented on rofi upstream?

If not, you can ask there first, it will end up here if the feature is accepted.
