### ISSUE TITLE
[BUG] text-color ignored and always black

### ISSUE THREAD

**Issue by kepi** [lbonn/rofi#27]
## Version

Version: 1.7.0-33-ga97ba40b (makepkg)

## Configuration

https://gist.github.com/kepi/8cb7b0b75dbf9a6db7003dcd93902037

## Launch Command

It is same for all modes. But i.e.

`rofi -show drun` 

## Steps to reproduce

1. Launch rofi

## What behaviour you see

- black text in every line

## What behaviour you expect to see

- text with color accroding to [.rasi theme](https://gitlab.com/jordiorlando/base16-rofi/-/raw/master/themes/base16-solarized-dark.rasi)

**Additional details:**
- my config https://github.com/kepi/dot.files/blob/master/rofi.org#rasi-config
- it started after update from git, no change to theme made
- I tried to change colors in rasi. Background is changing without problem, but `text-color` is ignored

![rofi](https://user-images.githubusercontent.com/105303/133897903-672392c1-46ea-47f8-974d-92081cabc5cc.png)

**Comment by ram02z** [comment]
This is due to an upstream change. See https://github.com/davatorium/rofi/issues/1397

**Comment by kepi** [comment]
Mea culpa. I tried to search issues but totally forgot to check the changelog. Thanks for hint, working like a charm.
