### ISSUE TITLE
[REQUEST] docs for window switching in sway

### ISSUE THREAD

**Issue by markstos** [lbonn/rofi#3]
The docs say _"Window mode when running in Wayland mode."_ doesn't work _"though it can be emulated in dmenu mode on some compositors (ie: Sway IPC)"_

How does the emulation with dmenu mode work on Sway? What's the syntax to use it. It could be helpful to add that to the docs.

**Comment by digital-mystik** [comment]
I was curious about this as well. I saw lbonn's gist (https://gist.github.com/lbonn/89d064cde963cfbacabd77e0d3801398) that enables window switching, but am not sure if that is something that can be implemented directly. I can run it as a script separately, but it would definitely by a nice addition to the base package.

**Comment by lbonn** [comment]
@digital-mystik It should be possible by using wlr-foreign-toplevel-management (see [comment](https://github.com/davatorium/rofi/pull/1139#issuecomment-657238398)) but I'm not planning to work on that at the moment. If you're interested, you can have a look.

I'm using https://github.com/lbonn/i3-focus-last#menu-mode now which also sorts the entries by focus order as a bonus (not sure if this can be achieved using the protocol).

**Comment by lbonn** [comment]
I've updated the README to refer to i3-focus-last
