### ISSUE TITLE
[BUG] icons are half-sized

### ISSUE THREAD

**Issue by markstos** [lbonn/rofi#4]
I tested this vs X11 rofi on 4k 27" display.

On X11 rofi, icons are the expected size.

On Wayland Rofi, the icons appear perhaps half the size-- very small and  hard to make out. 

It this a high DPI issue?

**Comment by lbonn** [comment]
I only have a 1440p monitor and tried icons with `rofi` and `rofi -x11` under sway. The behavior is the same with default and factor 2 scaling (`output HDMI-1 scale 2`). While icons are not very big, they seem to be the same size in both cases.

Could you give more details on what you have tried, preferably with screenshots?

**Comment by lbonn** [comment]
Maybe it has something to do with recent changes upstream and not wayland support? https://github.com/davatorium/rofi/issues/1185

**Comment by DaveDavenport** [comment]
In latest release the icon is no longer a hack in the textbox (that scaled to the size of the rendered font) but a separate widget with it own size options. (so you can make nice themes with large icons above/next to the text.).

**Comment by lbonn** [comment]
I'll close due to a lack of repro, and a susceptible cause. Please reopen if that's something else.
