### ISSUE TITLE
[BUG] Can't get window switcher to work under Wayland

### ISSUE THREAD

**Issue by justinesmithies** [lbonn/rofi#44]
### Rofi version (rofi -v)

1.7.2+wayland1-1-g07c801cd

### Configuration

https://gist.github.com/justinesmithies/4ce697cfad31c993125f3cdc89541003#file-config-rasi

### Launch command

rofi -modi combi,window -show combi -combi-modi drun

### Step to reproduce

I just cannot get the window switcher to show up. No matter what command options or config I use it always says:

Mode window is not found.

I used to use the X version of Rofi no problems with the window switcher.

### Expected behavior

I expected to see the application menu and the window switcher

### Actual behavior

Errors

**Comment by lbonn** [comment]
This is a known limitation: https://github.com/lbonn/rofi#wayland-support.

If you are on sway, you can use swayr or i3-focus-last with rofi.
