### ISSUE TITLE
[BUG] Installing from any release on Ubuntu fails at the `make` step

### ISSUE THREAD

**Issue by Gleland** [lbonn/rofi#46]
### Rofi version (rofi -v)

Latest release 1.7.2+wayland1 (reproducible on all three releases)

### Configuration

https://gist.github.com/Gleland/517864371010824dbbf58cfe62faed3d

### Launch command

make

### Step to reproduce

On the latest Ubuntu release (21.10, Impish Indri), with all the [listed packages](https://github.com/lbonn/rofi/blob/wayland/INSTALL.md) installed (they are typically `-dev` as described) , download` rofi-1.7.2+wayland1.tar.gz` locally and place in desired directory. 
Then follow the steps to build from source:
```bash
tar xvf  rofi-1.7.2+wayland1.tar.gz
cd rofi-1.7.2+wayland1/
mkdir build
autoreconf -i
cd build/
make
```

### Expected behavior

`make` and `make install` should produce a working version of rofi in /usr/local/bin.

### Actual behavior

See [this gist](https://gist.github.com/Gleland/517864371010824dbbf58cfe62faed3d) for the full output, the `make` command fails due to two undefined references:

```bash
/usr/bin/ld: source/rofi-rofi.o: in function `main':
/home/thogarre/workplace/rofi-1.7.2+wayland1/build/../source/rofi.c:897: undefined reference to `display_init'
/usr/bin/ld: source/rofi-view.o: in function `rofi_view_create':
/home/thogarre/workplace/rofi-1.7.2+wayland1/build/../source/view.c:1355: undefined reference to `display_set_input_focus'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2418: rofi] Error 1
make[1]: Leaving directory '/home/thogarre/workplace/rofi-1.7.2+wayland1/build'
make: *** [Makefile:1983: all] Error 2`
```

### Additional information

If there's any additional information that would be helpful, please let me know. Thank you for your time!

**Comment by Gleland** [comment]
Interestingly, I was able to build this successfully with the `meson` instructions, without any additional changes.

**Comment by lbonn** [comment]
Hi! This is a known issue as we have never really cared enough to update the autotools build.

But it was not made so clear in the README, so I have updated it in https://github.com/lbonn/rofi/commit/bd29749ab94b109c6aa883c95fac342e96665900.

#32 already covers this, so I am going to close this issue as duplicate. If someone wants to help with this, they are welcome.
