### ISSUE TITLE
[BUG] Erroneous character-encoding in default dumped theme

### ISSUE THREAD

**Issue by xsbee** [lbonn/rofi#52]
### Rofi version (rofi -v)

1.7.3+wayland1

### Configuration

https://gist.github.com/xsbee/5ddf3db9f37bcbfbddda78a8cbee7def

### Launch command

rofi -no-config -dump-theme > ~/.config/rofi/theme.rasi

### Step to reproduce

* Run `rofi -no-config -dump-theme > ~/.config/rofi/theme.rasi`
* Open with a text editor (e.g `helix`, `nano`).

### Expected behavior

Should be in ASCII format.

### Actual behavior

Includes random Unicode characters in places of numbers.

### Additional information

The command outputs the following in STDOUT:
```
(process:26911): GLib-CRITICAL **: 13:04:28.913: g_ascii_formatd: assertion 'strpbrk (format + 1, "'l%") == NULL' failed

(process:26911): GLib-CRITICAL **: 13:04:28.913: g_ascii_formatd: assertion 'strpbrk (format + 1, "'l%") == NULL' failed

(process:26911): GLib-CRITICAL **: 13:04:28.913: g_ascii_formatd: assertion 'strpbrk (format + 1, "'l%") == NULL' failed

(process:26911): GLib-CRITICAL **: 13:04:28.913: g_ascii_formatd: assertion 'strpbrk (format + 1, "'l%") == NULL' failed
```

**Comment by lbonn** [comment]
Interesting, it does not reproduce for me and this code was changed recently in upstream.

Could you try with upstream as well? And maybe running under valgrind?

Also, which commit revision are you using?

**Comment by lbonn** [comment]
Could be relevant https://github.com/davatorium/rofi/issues/1611

**Comment by lbonn** [comment]
Still cannot reproduce and no feedback, I'll close.

Please comment if this comes back.
