### ISSUE TITLE
Screenshot function

### ISSUE THREAD

**Issue by carnager** [lbonn/rofi#53]
### Rofi version (rofi -v)

Version 1.7.3

### Configuration

https://gist.github.com/carnager/e335b7bed63bb8dceb399e2ad92e87ce

### Launch command

rofi -show run -kb-screenshot "Alt+s"

### Step to reproduce

Run rofi like above
Hit Alt+s

### Expected behavior

rofi should save a picture of its own window and print the path to stdout.

### Actual behavior

rofi does not even react to the hotkey, even though it's an internal hotkey which *should* work on wayland?

### Additional information

Also tried vanilla rofi without the lbonn patches. There it works as expected.

**Comment by lbonn** [comment]
It's not yet implemented in wayland mode as it was not a priority.

Tagged as enhancement

**Comment by lbonn** [comment]
It is now working with a common function after merge from upstream: https://github.com/lbonn/rofi/commit/070c830a9215d1225d920c8e4f0433abb1699ca5

Thanks @davatorium!
