### ISSUE TITLE
[BUG] Missing "width" and "lines"options

### ISSUE THREAD

**Issue by luispabon** [lbonn/rofi#54]
### Rofi version (rofi -v)

1.7.3+wayland1-2-g396b13f5 (wayland)

### Configuration

https://gist.github.com/luispabon/f42ed198f973f9d71ab021dec98e88b0

### Launch command

rofi -show drun -width 10 -lines 3

### Step to reproduce

Basically as per launch command. 

### Expected behavior

A rofi window 20px by 3 lines should appear.

### Actual behavior

The window has the same size as merely running `rofi -show drun`

### Additional information

The options don't seem to have any effect, like they do on original rofi. They also don't show on `rofi -h` or the man page either.

**Comment by lbonn** [comment]
This has been changed in upstream rofi, you have to use themes for this purpose.

See the pinned issue there https://github.com/davatorium/rofi/issues/1397 and https://github.com/davatorium/rofi/issues/1542
