### ISSUE TITLE
[BUG] cannot change layout in rofi wayland

### ISSUE THREAD

**Issue by Tahvok** [lbonn/rofi#56]
### Rofi version (rofi -v)

1.7.3+wayland1

### Configuration

https://gist.github.com/Tahvok/8d571e4a33ddc736c25b97fa7a3f5d81

### Launch command

rofi -show run

### Step to reproduce

I'm using sway, so I setup my layout configuration as follows:
```
input * {
    xkb_layout "us,us"
    xkb_variant ",colemak"
    xkb_options "grp:shift_toggle,caps:backspace"
}
```
All apps work fine, I can change the layout.

However, sway work only using qwerty - no matter if I launch rofi before changing the layout, or trying to change the layout when rofi is running.

### Expected behavior

rofi supports different keyboard layouts

### Actual behavior

Rofi always types in qwerty

**Comment by LeGrosFaisan** [comment]
Hi,

I'm facing a similar issue. I'm using two different layouts, and I noticed that changing the layout before or while using rofi is not reflected when typing something.

I also noticed that rofi is using the **first** layout set in _xkb_layout_ 

I'm on ArchLinux and I'm using Hyprland, and I've tried updating libxkbcommon; however, it did not resolve the issue.

### Rofi version (rofi -v)
1.7.5+wayland1-38-gfd0ef6bc

**Comment by lbonn** [comment]
Yes, I can confirm this is quite annoying.

Looking into it...

**Comment by jaschiu** [comment]
> Yes, I can confirm this is quite annoying.
> 
> Looking into it...

Hi, what's the status of this?

**Comment by rj1** [comment]
i'm not sure if this is related, but using this fork of rofi is the only thing that doesn't respect the keyrate set in my sway config

e.g.

```
input "type:keyboard" {
    xkb_layout us
    repeat_delay 250
    repeat_rate 60
    xkb_options caps:escape
}
```

the rate in rofi is obviously much slower than anything else

edit: created separate issue @ https://github.com/lbonn/rofi/issues/81

**Comment by lbonn** [comment]
@rj1 I think this is probably another issue. Could you open a new one about this problem?
