### ISSUE TITLE
[REQUEST] Implement window switching using wlr_foreign_toplevel_management_unstable_v1

### ISSUE THREAD

**Issue by FriederHannenheim** [lbonn/rofi#57]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

I would like to switch windows in rofi

### How do you know that this problem exists today? Why is this important?

Switching windows is supported in mainline rofi

### Who will benefit from it?

Users without a dock or another way to switch windows. I am on wayfire which means I can have an overview of all windows using the scale plugin but sometimes I forget I have an app open and try to open it again using rofi and wonder why it doesn't work.

### Rofi version (rofi -v)

1.7.5

### Configuration

https://gist.github.com/FriederHannenheim/0fabc001a2caa54460bf53132661ed9d

**Comment by alebastr** [comment]
Coincidentally, I started working on that last week. I just need to rewrite my C++ prototype in C with GTypes and add some missing features before sending a pull request.
