### ISSUE TITLE
[BUG]  fullscreen: true;

### ISSUE THREAD

**Issue by exdeniz** [lbonn/rofi#6]
version: latest from aur.
If use in theme  fullscreen: true; like this:
```
window {
  transparency: "real";
  fullscreen: true;
  background-color: #282c34dd;
}
```
it's not working out very well.
![screenshot](https://user-images.githubusercontent.com/682584/89718669-29227780-d9c9-11ea-9190-e3b2896c11e7.png)

**Comment by lbonn** [comment]
Thanks for the report! It should be fixed in wayland branch's tip.

Though, the behavior differs slightly from x11's: it does not show on top of the bar.
