### ISSUE TITLE
[BUG]  doc/meson.build:3:4: ERROR: Program 'meson_build_manpages.sh' not found or not executable

### ISSUE THREAD

**Issue by evesdropper** [lbonn/rofi#60]
### Rofi version (rofi -v)

Version 1.7.5+Wayland1

### Configuration

-

### Launch command

-

### Step to reproduce

Can't install rofi - I just unzip the release, cd into the directory, and do `meson setup build`.

### Expected behavior

Meson should compile as usual and I should be able to build, which was how it was on Ubuntu.

### Actual behavior

I get the following error: `
doc/meson.build:3:4: ERROR: Program 'meson_build_manpages.sh' not found or not executable`.

**Comment by lbonn** [comment]
Thanks, `meson_build_manpages.sh` should have been part of the tarballs. I didn't test with go-md2man installed... As a workaround you can run configure/build with the package temporarily uninstalled.

After I have a look at #59, I'll try to make an intermediate release with the fix.
