### ISSUE TITLE
Cant install from AUR - some libnkutils/format-string error [BUG] 

### ISSUE THREAD

**Issue by erlonbie** [lbonn/rofi#63]
### Rofi version (rofi -v)

1.7.3.wayland1.r51.g1e8c22b4-1 (from AUR)

### Configuration

Irrelevant (can't install)

### Launch command

yay -S rofi-lbonn-wayland-git

### Step to reproduce

yay -S rofi-lbonn-wayland-git

### Expected behavior

Install on the system

### Actual behavior

3/18 libnkutils:format-string / libnkutils format-string module tests         ERROR           0.04s   exit status 1
MALLOC_PERTURB_=185 /home/erlonbie/.cache/yay/rofi-lbonn-wayland-git/src/build/subprojects/libnkutils/nk-format-string.test --tap

![image](https://user-images.githubusercontent.com/50176483/193317051-e92199b1-a26c-4c19-8d66-92a1a6ef60a6.png)

### Additional information

I installed this package in a very similar machine (almost same programs installed) and had no issue.

**Comment by Celti** [comment]
This is an issue in libnkutils that does not appear to have been fixed in latest master. Commit [7074122](https://github.com/GNOME/glib/commit/7074122f308b7b3402fba250f2010778fdad6eff) in glib changed the default format string to use numbers padded with `U+2007 FIGURE SPACE` instead of with normal spaces; the corresponding test in libnkutils needs to be updated to match.

**Comment by Celti** [comment]
I've properly reported this [against libnkutils](https://github.com/sardemff7/libnkutils/issues/4). This issue should probably be closed in favour of one against upstream rofi to update the libnkutils version after the underlying issue is resolved.

**Comment by sardemff7** [comment]
Fixed in upstreams [libnkutils](https://github.com/sardemff7/libnkutils/commit/7b3a80a1e8b958b8fd42f74d973b28b4eb495fbc) and [rofi](https://github.com/davatorium/rofi/commit/5a979b0afe868d3489013619a22394af96298509) :slightly_smiling_face:

**Comment by erlonbie** [comment]
Trying to install through AUR and getting the same error.

I noticed a comment from @Celti [here](https://aur.archlinux.org/packages/rofi-lbonn-wayland) mentioning --nocheck flag. How do I use it?

**Comment by lbonn** [comment]
Should be fixed now, please reopen in case of further problems.

But yes, it would be better to skip test runs during the AUR package generation

**Comment by norris-young** [comment]
This

> Should be fixed now, please reopen in case of further problems.
> 
> But yes, it would be better to skip test runs during the AUR package generation

Fixed, but it won't be pushed to AUR until you tag a new release.
