### ISSUE TITLE
[BUG] Fullscreen (with waybar) 

### ISSUE THREAD

**Issue by semi710** [lbonn/rofi#64]
### Rofi version (rofi -v)

Version: 1.7.5+wayland1-37-ge861df39 (makepkg)

### Configuration

https://gist.github.com/niksingh710/55c15cef4d66463baded78e6e637297e

### Theme

https://gist.github.com/niksingh710/0feacf1205ea3b3844243220412712a2

### Launch command

/usr/bin/ls | rofi -dmenu -theme-str 'window{fullscreen:true;}prompt{enabled:false;}'

### Step to reproduce

Just execute the command in terminal.

### Expected behavior

Should Take the entire Screen.

### Actual behavior

Does not go over the waybar.
Is there any way by which I can specify which layer to use? any way

### Additional information

Using Hyland as wm.

**Comment by lbonn** [comment]
It should be fixed in master
