### ISSUE TITLE
[BUG] Rofi faulting after updating to KDE 5.26

### ISSUE THREAD

**Issue by waicool20** [lbonn/rofi#65]
### Rofi version (rofi -v)

e861df39f265b14b035099108e515be461225068

### Configuration

N/A

### Theme

N/A

### Launch command

rofi

### Step to reproduce

Launch rofi

### Expected behavior

Does not crash

### Actual behavior

Crashes with
```
$ build/rofi                                                                                         
listener function for opcode 1 of wl_data_offer is NULL
[1]    203080 IOT instruction (core dumped)  build/rofi
```

### Additional information

I've run into an issue where rofi crashes when launched after updating to the recently released KDE 5.26, I've managed to fix the issue temporarily with these changes to the code https://github.com/waicool20/rofi/commit/5f207ae895ae4fb23074bc7da8692c65c8cb7c15
I'm not sure if this is the right change to be making since I'm not familiar with wayland (eg. might not work if I revert back to older KDE or other DEs) hence I've not put up a PR.

**Comment by lbonn** [comment]
Thanks for the report! Indeed, looks like something is missing.

**Comment by ghost** [comment]
For me the fix works perfectly, so I'd love to see it being merged so I can install the version in the AUR again

**Comment by lbonn** [comment]
@30p87 @waicool20 did you try to see if pasting from clipboard still works after this change?

If so, I think you can open a PR.

**Comment by waicool20** [comment]
Seems like clipboard pasting still works, just worried the code changes aren't backwards compatible and will break things for people still on older versions of wayland/kde

**Comment by lbonn** [comment]
It should be fine, the handlers also exist in older versions.
