### ISSUE TITLE
[BUG] -monitor -1 does't behave as it should

### ISSUE THREAD

**Issue by Zeioth** [lbonn/rofi#73]
### Rofi version (rofi -v)

1.7.5

### Configuration

https://pastebin.com/GCeK1v8k

### Theme

https://pastebin.com/vQYnTn6D

### Launch command

rofi -show drun -monitor -1

### Step to reproduce

On sway, run 'rofi -show drun' having at least 2 monitors. → (I have 6)

### Expected behavior

Rofi opens in the active monitor.

### Actual behavior

Rofi will fail to detect the active monitor, and it will display on a different one.

**Comment by mindrunner** [comment]
Same here! I just recently switched back to rofi from wofi. Maybe this is an issue with sway 1.8?

**Comment by mindrunner** [comment]
According to 
https://github.com/lbonn/rofi/issues/39

this is not supported :(

Is that still the case?

**Comment by lbonn** [comment]
Actually, it looks similar to the problem in https://github.com/lbonn/rofi/issues/39#issuecomment-938070477, are you both actually running this fork and not upstream rofi? From the version string in the description, it looks like not.

`-monitor -1` is not supported but usually rofi (this fork) shows on the active screen in wayland.

**Comment by mindrunner** [comment]
Wow, I was so sure I am using your version. Turned out that there were some issues installing it from `aur`, so I was using the 'official' one. Switched to the wayland fork now and it seems to work better :)

**Comment by lbonn** [comment]
Thanks! Then probably nothing to see here :)
