### ISSUE TITLE
[BUG] cant compile rofi with makedeb because gdk-pixbuf 2.0 is missing even though this dependency is already installed

### ISSUE THREAD

**Issue by fislysandi** [lbonn/rofi#74]
### Rofi version (rofi -v)

1.7.5 

### Configuration

none

### Theme

none

### Timing report

none

### Launch command

none

### Step to reproduce

1. install a debian testing distrobox container or a vm
2. install makedeb stable
3. run the modified arch PKGBUILD i made (https://controlc.com/6ddbbf4b)
cant share via pastebin since its offensiv 😡
4. get the compilation issue

### Expected behavior

i expect rofiwl to compile into a nice debian package

### Actual behavior

rofiwl fails to compile into a debian package

### Additional information

i copied the PKGBUILD from AUR and modified it to have debian dependencies  but i encountered this issue.

dont know how to solve it

if its not the rofi issue then i will report it to makedeb github https://github.com/makedeb/makedeb

screenshots 
![vmware_n5uloy4AZJ](https://user-images.githubusercontent.com/45166203/214252199-2fb8dd9c-3249-4ae1-be7b-7295add03079.png)
![vmware_m4188VTvbS](https://user-images.githubusercontent.com/45166203/214252212-4fea81fe-26f0-414d-a064-35621ba623fc.png)

**Comment by fislysandi** [comment]
after this issue would be resolved i can finally ditch x11 and port my dmenu scripts and use hyprland ^_^

**Comment by lbonn** [comment]
You are having problem with your packaging tool. Sorry but we can't support every one of them, I guess you will have to ask people familiar with makedeb.
