### ISSUE TITLE
[BUG] Layer shell protocol??

### ISSUE THREAD

**Issue by midpl0x** [lbonn/rofi#80]
### Rofi version (rofi -v)

1.7.5+wayland1

### Configuration

Unavailable

### Theme

none

### Timing report

unavailable

### Launch command

unavailable

### Step to reproduce

rofi-anything will show the following message: 

(process:xxx) Wayland-ERROR **: ´timestamp´: Rofi on Wayland requires support for the layer shell protocol

I'm not a native Linux-user, but I like it, and I am learning every day. 

I've installed built and installed wlroots as well as Sway. And I dont even know if Sway is necessary? It launches just fine though. The only "issue" seems to be with rofi, I guess? 

And it seems as if theres a `wlr-layer-shell-unstable-v1.xml` in my `~/.config/rofi-1.7.5+wayland1/protocols`-folder. 

Am I stupid? 

### Expected behavior

Normal running rofi.

### Actual behavior

Wayland-Error as described.

**Comment by lbonn** [comment]
What is your current desktop environment and Linux flavor? Did you compile rofi yourself?

Your current environment does not seem to support rofi with wlroots, so you might have to fall back to regular X11 rofi https://github.com/davatorium/rofi.
Launching sway from your DE is possible and I think that is what you tried..? But you would need to run sway as your main environment.

**Comment by midpl0x** [comment]
Yeah, it seems as if it would've been worth noting that I'm running Linux though WSL. It seems as if there are certain issues with having stuff work properly at times. 

I think I'll just run it through VMware.  It seems a lot less complicated then. Thank you for the reply though!
