### ISSUE TITLE
[BUG] Can't Use Touch screen after rofi is running

### ISSUE THREAD

**Issue by awarewen** [lbonn/rofi#83]
### Rofi version (rofi -v)

Version: 1.7.5+wayland2-1-gff2338c3 (makepkg)

### Configuration

https://fars.ee/DFVN or https://gist.github.com/awarewen/15906a00d39bcdeef56a8eb961f51191

### Theme

https://fars.ee/bPK8 or https://gist.github.com/awarewen/f5f36dc641200cac97c653021ddaa8cb

### Launch command

rofi -show run

### Step to reproduce

Step 1:
Commands 1 run (start rofi and wvkbd):
`lisgd -d /dev/input/event13 -g "1,TR,*,*,R,notify-send next worksapce && rofi -show run && wvkbd-mobintl -L 300"`

Commands 2 run (swipe right change workspace):
`lisgd -d /dev/input/event13 -g "1,RL,*,*,R,notify-send next worksapce && hyprctl dispatch workspace +1 "`

Commands 3 run (swipe left change workspace):
`lisgd -d /dev/input/event13 -g "1,LR,*,*,R,notify-send next worksapce && hyprctl dispatch workspace -1 "`

Step 2:
swipe up the screen, 'rofi' is start running but 'wvkbd' doesn't run at the same time. And I can't start 'wvkbd' or other programs by clicking the button on 'waybar'. Swipe the screen left or right  the workspace change runs normally.

Step 3:
When i close the 'rofi', i can run 'wvkbd' by clicking the button on 'waybar'

https://github.com/davatorium/rofi/assets/53365857/da1c35e9-f2e3-475e-97c1-544edb54e475

### Expected behavior

I want to type in rofi via the virtual on-screen keyboard, and scroll through the 'rofi' list via touch screen. SO, i need 'rofi' start with 'wvkbd' at the same time.

### Actual behavior

'rofi' can't start with 'wvkbd' at the same time, and i can't start 'wvkbd' by clicking the button on  waybar

### Additional information

https://github.com/davatorium/rofi/discussions/1880

- WM:  hyprland
Hyprland, built from branch main at commit 261c3307f70d14e5bbc7d4113b4ee6dac9e4b627 dirty (internal: cleanup headers in helpers/).
Tag: v0.28.0-11-g261c3307

flags: (if any)

- virtual keyboard: wvkbd
wvkbd 0.12-1

**Comment by lbonn** [comment]
wvkbd is a [layer shell on top layer](https://github.com/jjsullivan5196/wvkbd/blob/98e6c43d547dfed25c17b7ff0d766b041ef62c16/main.c#L39), whereas we are using overlay.

We already had discussions and back-and-forth here https://github.com/lbonn/rofi/issues/12. Might need some revisiting, possibly a configuration parameter as well.

You can also try to move wvkbd to overlay layer as well and see if it behaves better (haven't checked hyprland behavior in this case). You will need to recompile it.

**Comment by awarewen** [comment]
> wvkbd is a [layer shell on top layer](https://github.com/jjsullivan5196/wvkbd/blob/98e6c43d547dfed25c17b7ff0d766b041ef62c16/main.c#L39), whereas we are using overlay.
> 
> We already had discussions and back-and-forth here #12. Might need some revisiting, possibly a configuration parameter as well.
> 
> You can also try to move wvkbd to overlay layer as well and see if it behaves better (haven't checked hyprland behavior in this case). You will need to recompile it.

Thanks, got it.

**Comment by lbonn** [comment]
@awarewen I did not mean the bug / behavior is not valid, just tried to explore the reasons. Have you tried patching wvkbd and did it work?

**Comment by awarewen** [comment]
> @awarewen I did not mean the bug / behavior is not valid, just tried to explore the reasons. Have you tried patching wvkbd and did it work?

i changed wvkbd's `layer` to `OVERLAY`,it doesn't work, when i open wvkbd and rofi at the same time, touch-screen isn't work.

https://github.com/lbonn/rofi/assets/53365857/7a942e3a-0746-422d-9af4-fa22e98ea043

![图片](https://github.com/lbonn/rofi/assets/53365857/5ce0dc2d-4f85-45a3-af44-e6452dc1d385)

Command runs 1 (open wvkbd and rofi at the same time)

Command runs 2 (swipe the screen R-to-L , only wvkbd working): `lisgd -d /dev/input/event8 -g "1,RL,*,*,R,wvkbd-mobintl -L 300 && rofi -show drun && notify-send next worksapce "`

Command runs 3 (like command 2): `lisgd -d /dev/input/event8 -g "1,RL,*,*,R,notify-send next worksapce && wvkbd-mobintl -L 300 && rofi -show drun"`

Command runs 4 (rofi first then is wvkbd, but it didn't running at the same time.) : `lisgd -d /dev/input/event8 -g "1,RL,*,*,R,notify-send next worksapce && rofi -show drun && wvkbd-mobintl -L 300"`
