### ISSUE TITLE
[BUG] Rofi does not honour `-m -4` etc.

### ISSUE THREAD

**Issue by gabyx** [lbonn/rofi#98]
### Rofi version (rofi -v or git commit in case of build issue)

1.7.5

### Configuration

https://gist.github.com/gabyx/2a2a2d11d26a83ca7ee20f2673abee84

### Theme

https://gist.github.com/gabyx/628164a5eecfbb0284dd7f91ab0d8463

### Launch command

rofi -modi run,drun,window -show drun -show-icons -monitor "-4"

### Step to reproduce

* Run `rofi -modi run,drun,window -show drun -show-icons -monitor "-4"` in `sway`
* The window does not honour my selected windows/monitor or anything, basically all options `-1/2/3/4` have no effect.
* Only `-monitor primary` actually works, otherwise for me the second monitor from `rofi -h` is used:
  
```
Monitor layout:
              ID: 0
            name: HDMI-A-2
        position: 0,0
            size: 2560,1440
            size: 600mm,340mm  dpi: 108,108

              ID: 1
            name: DP-2
        position: 2560,0
            size: 1920,1080
            size: 530mm,300mm  dpi: 92,91
  ```
  

### Expected behavior

Options `-m` should work correctly under sway

### Actual behavior

No effects of `-m -1` or any other negative numbers.

### Additional information

My nixos setup:

https://github.com/gabyx/dotfiles

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
@gabyx afaik, this not possible with the wlr protocol to follow the mouse pointer. With the default behavior, the compositor chooses the monitor for us, presumably the currently focused one.

In #111, support was added to choose a monitor by name

**Comment by variasdesign** [comment]
I'm sorry for necroing this issue, but I have a keyboard-centric workflow and Rofi following the mouse pointer by default messes with it. What option can we use to make Rofi ignore the focus of the mouse pointer? Thanks.

EDIT: I've found a workaround (at least on Hyprland):
`hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name')`

This command will output the monitor with the currently focused window, ignoring mouse pointer (assuming follow_mouse = 0).
